"""
file_extractor.py — Incremental file extraction with:
  - Shared ignore / extension lists from repo_scanner
  - Per-file size limit
  - Total source size limit
  - Generated-content detection (auto-generated header)
  - Priority-based ordering (README first, tests last)
  - Real statistics returned
  - Wall-clock timeout on the directory walk (mirrors repo_scanner)
  - Optional pre-scanned file list to avoid double rglob on large repos
"""

import time
from pathlib import Path

from services.repo_scanner import (
    IGNORED_DIRECTORIES,
    SOURCE_EXTENSIONS,
    MAX_FILE_SIZE_BYTES,
    MAX_TOTAL_SOURCE_MB,
    MAX_FILES_TO_ANALYZE,
    SCAN_WALK_TIMEOUT_SECONDS,
    _priority,
    _is_likely_generated_or_minified,
)


# ── Generated-file header patterns ───────────────────────────────────────────

_GENERATED_MARKERS = (
    b"// DO NOT EDIT",
    b"// Code generated",
    b"# DO NOT EDIT",
    b"# Generated by",
    b"/* Generated by",
    b"// This file is auto-generated",
    b"// Autogenerated by",
    b"// This is a generated file",
    b"// GENERATED CODE",
    b"# This file was auto-generated",
)


def _is_generated_content(path: Path) -> bool:
    """Check first 512 bytes for auto-generated markers."""
    try:
        header = path.read_bytes()[:512]
        return any(marker in header for marker in _GENERATED_MARKERS)
    except OSError:
        return False


def extract_files(repo_path: str, pre_scanned_files: list[str] | None = None) -> list[dict]:
    """
    Extract text content from repository files, incrementally and within limits.

    Returns a list of {file, content} dicts.

    Parameters
    ----------
    repo_path
        Absolute or relative path to the repository root.
    pre_scanned_files
        Optional list of relative file paths (as returned by scan_repository).
        When provided the rglob walk is skipped entirely — this dramatically
        speeds up extraction on large repos (avoids a second 60-second walk).

    Bounded by SCAN_WALK_TIMEOUT_SECONDS when the walk is needed — the
    directory walk stops after this many seconds so huge repos (Kubernetes)
    cannot hang this stage forever.
    """
    repo = Path(repo_path)

    if not repo.exists():
        return []

    documents: list[dict] = []
    total_bytes = 0

    # ── Fast path: caller supplied the file list from scan_repository ────────
    if pre_scanned_files is not None:
        # Sort by priority using full paths, then extract
        full_paths = [(repo / rel, rel) for rel in pre_scanned_files]
        full_paths.sort(key=lambda t: _priority(t[0]))

        for path, rel_str in full_paths:
            if len(documents) >= MAX_FILES_TO_ANALYZE:
                break
            try:
                file_size = path.stat().st_size
            except OSError:
                continue
            if file_size == 0 or file_size > MAX_FILE_SIZE_BYTES:
                continue
            if (total_bytes + file_size) > MAX_TOTAL_SOURCE_MB * 1024 * 1024:
                break
            if _is_generated_content(path):
                continue
            try:
                content = path.read_text(encoding="utf-8", errors="ignore").strip()
            except Exception:
                continue
            if not content:
                continue
            total_bytes += file_size
            documents.append({
                "file": rel_str.replace("\\", "/"),
                "content": content,
            })
        return documents

    # ── Slow path: full rglob walk (used when scan results not available) ────
    candidate_files: list[Path] = []
    walk_start = time.monotonic()

    for path in repo.rglob("*"):
        # Hard wall-clock cut-off on the walk itself
        if time.monotonic() - walk_start > SCAN_WALK_TIMEOUT_SECONDS:
            break

        if not path.is_file():
            continue

        try:
            relative = path.relative_to(repo)
        except ValueError:
            continue

        parts_lower = [p.lower() for p in relative.parts[:-1]]

        if any(part in IGNORED_DIRECTORIES or part.startswith("bazel-") for part in parts_lower):
            continue

        suffix = path.suffix.lower()

        if suffix not in SOURCE_EXTENSIONS and path.name not in {
            "Makefile", "Dockerfile", "Gemfile", "Procfile",
        }:
            continue

        if _is_likely_generated_or_minified(path):
            continue

        candidate_files.append(path)

    # Sort by priority
    candidate_files.sort(key=_priority)

    for path in candidate_files:
        if len(documents) >= MAX_FILES_TO_ANALYZE:
            break

        try:
            file_size = path.stat().st_size
        except OSError:
            continue

        if file_size == 0:
            continue

        if file_size > MAX_FILE_SIZE_BYTES:
            continue

        if (total_bytes + file_size) > MAX_TOTAL_SOURCE_MB * 1024 * 1024:
            break

        if _is_generated_content(path):
            continue

        try:
            content = path.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue

        content = content.strip()
        if not content:
            continue

        total_bytes += file_size

        try:
            rel = str(path.relative_to(repo)).replace("\\", "/")
        except ValueError:
            continue

        documents.append({
            "file": rel,
            "content": content,
        })

    return documents
